#!/bin/bash
rm /etc/apt/sources.list
cp /home/alan/Modelos/debian-xfce/sources.list /etc/apt/
apt update && apt upgrade
rm /etc/profile
cp /home/alan/Modelos/debian-xfce/profile /etc
source /etc/profile
cd /home/alan/Modelos/debian-xfce/
dpkg -i google-chrome-stable_current_amd64.deb
apt -f install
dpkg -i google-chrome-stable_current_amd64.deb
dpkg -i micro-2.0.11-amd64.deb
dpkg -i code_1.75.1-1675893397_amd64.deb
apt install exa
apt install timeshift
apt install xclip
apt install rar unrar
apt install neofetch
apt install git
apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
